version: 2

project_name: my-ls

builds:
  - id: my-ls
    binary: my-ls
    main: ./cmd/my-ls
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: default
    formats: [binary]
    builds:
      - my-ls

release:
  draft: false
